Renewal
eccubevn/category-content-plugin pull request #3
Opened 2016-10-26 08:54 UTC by hoand-vn

for travis checking

2016-11-01 01:38 UTC, ryo-endo requested changes

2016-11-01 01:38 UTC, ryo-endo commented on PluginManager.php
>      public function update($config, $app)
- [ ] need migration in update function.

2016-11-01 01:38 UTC, ryo-endo commented on config.yml
> +version: 0.0.4
- [ ] please, change 1.0.0

2016-11-01 01:39 UTC, ryo-endo commented
- [ ]  please don't insert white-space in twig filters. `CategoryContent.content | raw` -> `CategoryContent.content|raw`

https://github.com/eccubevn/category-content-plugin/pull/3/files#diff-bca7e7f8fed5d91adb42d670999554a5R78

2016-11-01 09:14 UTC, hoand-vn commented on config.yml
> +version: 0.0.4
fixed

2016-11-01 09:41 UTC, hoand-vn commented on PluginManager.php
>      public function update($config, $app)
fixed

2016-11-24 03:43 UTC, ryo-endo requested changes
## bug(既存)
フロント画面で、挿入結果の位置が、他の項目とズレているのを修正してください。
![image](https://cloud.githubusercontent.com/assets/16891862/20586043/a7ee1d46-b243-11e6-988e-3d37e6f1cb36.png)

2016-11-24 03:47 UTC, ryo-endo requested changes
## miss?
`<!--# category-content-plugin-tag #-->`と書いてある位置に挿入する対応をお願いします。
（Event/LegacyEvent両方）

2016-11-24 03:49 UTC, ryo-endo requested changes
## rule
フォルダ名`Utils`→`Util`に変更してください。
理由：フォルダはEC-CUBE本体のフォルダ名と合わせる。

2016-11-24 03:51 UTC, ryo-endo commented on Utils/Version.php
> +    public static function supportNewHookPoint()
## impl error
`supportNewHookPoint`→`isSupportNewHookPoint`

2016-12-02 01:15 UTC, chihiro-adachi commented on ServiceProvider/CategoryContentServiceProvider.php
>          $app['category_content.repository.category_content'] = $app->share(function () use ($app) {
fix please 

category_content.repository.category_content
->
eccube.plugin.category_content.repository.category_content

2016-12-02 01:17 UTC, chihiro-adachi commented on ServiceProvider/CategoryContentServiceProvider.php
> +        $app['translator'] = $app->share($app->extend('translator', function (Translator $translator, \Silex\Application $app) {
translatorへの追加は、以下のコードだけでよいです。

`$app['translator']->addResouece('yaml', $file, $locale); `

2016-12-02 01:21 UTC, chihiro-adachi commented
event.yml
```
# admin page event
admin.product.category.index.initialize:
    - [onFormInitializeAdminProductCategory, NORMAL]
admin.product.category.index.complete:
    - [onAdminProductCategoryEditComplete, NORMAL]
```

`onFormInitializeAdminProductCategory`は、以下に修正お願いします。

`onAdminProductCategoryFormInitialize`

2016-12-02 08:33 UTC, ryo-endo requested changes
### 実装モレ
Event.phpが`<!--# category-content-plugin-tag #-->`に対応できていない。

2016-12-02 10:16 UTC, hoand-vn commented
Fixed review of Adachi san + Endo san 
<!--# category-content-plugin-tag #--> ( committed before )
Thank for your support.

2016-12-05 02:23 UTC, ryo-endo commented
test is broken by a436432.

2016-12-05 03:48 UTC, closed without merging

2016-12-05 03:51 UTC, chihiro-adachi commented
from is_null to `!`  changed. why ?